import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sm Link",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (

    <html lang="en">

      <body className={`antialiased`}>

        <Toaster richColors />
        
        {children}

      </body>

    </html>

  );
}
