import { SpeedInsights } from "@vercel/speed-insights/next"
import { Lexend } from "next/font/google"
import { Toaster } from "sonner";
import type { Metadata } from "next";
import { ReduxProvider } from "@/store/ReduxProvider";
import { TooltipProvider } from "@/components/shadcn/tooltip";
import "./globals.css";

export const metadata: Metadata = {
  title: "SmLink",
  description: "Generated by create next app",

  other: {
    google: "notranslate"
  }
};

const lexend = Lexend({ 
  subsets: ["latin"], 
  weight: ['200', '300', '400', '600', '700'], 
})

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  return (

    <html lang="en">
      <body className={`antialiased ${lexend.className} overflow-y-auto min-h-screen relative `}>
        <SpeedInsights />

        <TooltipProvider>
          <ReduxProvider>
            <Toaster richColors />
            {children}
          </ReduxProvider>
        </TooltipProvider>
      </body>
    </html>

  );
}
