import { MainMenu } from "@/components/home/menu/MainMenu";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Lexend } from "next/font/google"
import { Toaster } from "sonner";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sm Link",
  description: "Generated by create next app",
};

const lexend = Lexend({ subsets: ["latin"] })

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  return (

    <html lang="en">
      <body className={`antialiased ${lexend.className} overflow-y-auto min-h-screen relative`}>
        <SpeedInsights />
        <MainMenu />
        <Toaster richColors />
        {children}
      </body>
    </html>

  );
}
